config/routes.rb
Rails.application.routes.draw do

  resources :users
  root 'static_pages#home'

  resources :bills do
  	collection { post :import }
  end

  namespace :admin do
	  root 'bills#index'
		resources :bills do
	  	collection { post :import}
		end
	  #mount Idioma::Engine => "/idioma"
	end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bill.rb
class Bill < ApplicationRecord
	require 'csv'
	self.per_page = 12

	def self.search(search)
		where("title ILIKE ? OR \"bill_num\" ILIKE ? OR committee_primary_origin ILIKE ? or category ILIKE ?", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
	end

	#This updates existing bills and creates new bills using the uploaded CSV file. It is very verbose due to having lots of columns.
	#In the future I may look to simplify this
	def self.import(file)
		if (file == nil)
			return
		end

    CSV.foreach(file.path, {headers: true, :encoding => 'windows-1251:utf-8'}) do |row|

    	if row["Title"].include?("Creation of a State Debt")
    		next
    	end

    	bills = Bill.where(bill_num: row["Bill Number"])
    	if bills.count != 0
    		bill = bills.first
    	else
      	bill = Bill.new
      end

    	bill.bill_num = row["Bill Number"]
    	bill.chapter_num = row["Chapter Number (nnnn)"]
    	bill.cross_file = row["XFile Bill Number"]
    	bill.sponsor = row["Sponsor"]
    	bill.synopsis = row["Synopsis"]
    	bill.title = row["Title"]
    	bill.current_status = row["Current Status"]
    	bill.first_reading_date_origin = row["First Reading Date - House of Origin"]
    	bill.committee_primary_origin = row["Committee Primary - House of Origin"]
    	bill.primary_hearing_date_origin = row["Hearing Date Primary - House of Origin"]
    	bill.primary_hearing_time_origin = row["Hearing Time Primary - House of Origin"]
    	bill.committee_secondary_origin = row["Committee Secondary - House of Origin"]
    	bill.secondary_hearing_date_origin = row["Hearing Date Secondary - House of Origin"]
    	bill.secondary_hearing_time_origin = row["Hearing Time Secondary - House of Origin"]
    	bill.report_date_origin = row["Report Date - House of Origin"]
    	bill.report_action_origin = row["Report Action - House of Origin"]
    	bill.secondary_reading_date_origin = row["Second Reading Date - House of Origin"]
    	bill.secondary_reading_action_origin = row["Second Reading Action - House of Origin"]
    	bill.third_reading_date_origin = row["Third Reading Date - House of Origin"]
    	bill.third_reading_action_origin = row["Third Reading Action - House of Origin"]
    	bill.first_reading_date_opposite = row["First Reading Date - Opposite House"]
    	bill.committee_primary_opposite = row["Committee Primary - Opposite House"]
    	bill.primary_hearing_date_opposite = row["Hearing Date Primary - Opposite House"]
    	bill.primary_hearing_time_opposite = row["Hearing Time Primary - Opposite House"]
    	bill.committee_secondary_opposite = row["Committee Secondary - Opposite House"]
    	bill.secondary_hearing_date_opposite = row["Hearing Date Secondary - Opposite House"]
    	bill.secondary_hearing_time_opposite = row["Hearing Time Secondary - Opposite House"]
    	bill.report_date_opposite = row["Report Date - Opposite House"]
    	bill.report_action_opposite = row["Report Action - Opposite House"]
    	bill.secondary_reading_date_opposite = row["Second Reading Date - Opposite House"]
    	bill.secondary_reading_time_opposite = row["Second Reading Action - Opposite House"]
    	bill.third_reading_date_opposite = row["Third Reading Date - Opposite House"]
    	bill.third_reading_action_opposite = row["Third Reading Action - Opposite House"]
    	bill.interaction_between_chambers = row["Interaction Between Chambers"]
    	bill.passed_by_mga = row["Passed by MGA"]
    	bill.emergency_bill = row["Emergency Bill"]
    	bill.constitutional_amendment = row["Constitutional Amendment"]
    	bill.broad_subject_name = row["Broad Subject Name"]
    	bill.broad_subject_code = row["Broad Subject Code"]
    	bill.year_session = row["year_session"]
    	bill.status_current_as_of = row[" status current as of"]

      bill.save!
    end
  end

end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  #the following commented out code will be used to set up admin logins in the future
  #before_action :require_login

  #private
    #def not_authenticated
    #end
end

app/controllers/admin/bills_controller.rb
class Admin::BillsController < Admin::BaseController
  before_action :set_bill, only: [:show, :edit, :update, :destroy]

  def index  
    if params[:search]
      @bills = Bill.search(params[:search]).paginate(:page => params[:page]).order(bill_num: :asc)
    else
      @bills = Bill.all.paginate(:page => params[:page]).order(bill_num: :asc)
    end
  end

  def show
    @xfile = Bill.where(bill_num: @bill.cross_file).first
  end

  def new
    @bill = Bill.new
  end

  def edit
    @xfile = Bill.where(bill_num: @bill.cross_file).first
  end

  def create
    @bill = Bill.new(bill_params)

    respond_to do |format|
      if @bill.save
        format.html { redirect_to @bill, notice: 'Bill was successfully created.' }
        format.json { render :show, status: :created, location: @bill }
      else
        format.html { render :new }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @bill.update(description: params[:description], vip: params[:vip], category: params[:category])
    redirect_to admin_bill_path(@bill)
  end

  def destroy

  end

  def import
    Bill.import(params[:file])
    redirect_to admin_root_path
  end

  private
    def set_bill
      @bill = Bill.find(params[:id])
    end

    def bill_params
      params.permit(:bill, :description, :vip, :category)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_action :set_bill, only: [:show, :edit, :update, :destroy]

  def index  
    if params[:search]
      @bills = Bill.search(params[:search]).paginate(:page => params[:page]).order(bill_num: :asc)
    else
      @bills = Bill.all.paginate(:page => params[:page]).order(bill_num: :asc)
    end
  end

  def show
    @xfile = Bill.where(bill_num: @bill.cross_file).first
  end

  def new
    @bill = Bill.new
  end

  def create
    @bill = Bill.new(bill_params)

    respond_to do |format|
      if @bill.save
        format.html { redirect_to @bill, notice: 'Bill was successfully created.' }
        format.json { render :show, status: :created, location: @bill }
      else
        format.html { render :new }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  def update

  end

  def destroy

  end

  private
    def set_bill
      @bill = Bill.find(params[:id])
    end

    def bill_params
      params.permit(:bill, :description, :vip, :category)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    bills = Bill.order("RANDOM()").where(vip: true)
    if bills.length < 2
      if bills.length == 0
        @billOne = Bill.first
        @billTwo = Bill.last
      else
        @billOne = bills.first
        @billTwo = Bill.where(vip: false).first
      end
    else
      @billOne = bills.first
      @billTwo = bills.last
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/bills/edit.erb
<%#This page shows very rudimentary information and it isn't formatted that well at the moment.%>
<div style="text-align:center">
	<h4><%=@bill.bill_num + ": " + @bill.title%></h4>
		<%if @xfile != nil%>
		<h4><%=link_to "This bill has a cross filed bill: " + @xfile.bill_num + ". Click here to view that bill", edit_admin_bill_path(@xfile)%></h4>
	<%end%>
	<h4>Hearing Date Origin: <%=@bill.primary_hearing_date_origin%></h4>
	<h4>Hearing Date Opposite: <%=@bill.primary_hearing_date_opposite%></h4>
	<h4>Synopsis:</h4><%=@bill.synopsis%>

	<%= form_tag admin_bill_path(@bill), method: "put" do %>
		<h4>Category:</h4>
			<%= text_field_tag :category, @bill.category %>
		<br><br>
		<%= hidden_field_tag :vip, false %>
		<%= label_tag "Is this a VIP Bill?" %>
		<%= check_box_tag :vip, true, @bill.vip%>
	  <h4>Bill Description:</h4>
	  	<%= text_area_tag :description, @bill.description, size: "200x10"%><br>
	  	<%= submit_tag "Submit Bill" %>
	<% end %>
</div>
<%=link_to "View Show page", admin_bill_path(@bill)%>
<br>
<%=link_to "Back to Index", admin_bills_path%>

app/views/admin/bills/index.erb
<div class="container-fluid">
	<div>
  <h4>Import Bills</h4>
  <%= form_tag import_admin_bills_path, multipart: true do %>
    <%= file_field_tag :file %>
    <%= submit_tag "Import CSV" %>
  <% end %>
</div>
  <div class="row">
    <div class="col-md-10">
    	<table class="table table-striped">
		    <thead>
		      <tr>
		        <th style="width:10%">Bill Number</th>
		        <th style="width:40%">Title</th>
		        <th style="width:30%">Primary Committee</th>
		        <th>Category</th>
		      </tr>
		    </thead>
		    <tbody>
		    	<% @bills.each do |bill| %>
		      <tr>
		        <td><%= link_to bill.bill_num, edit_admin_bill_path(bill) %></td>
		        <td><%= bill.title %></td>
		        <td><%= bill.committee_primary_origin %></td>
		        <td><%= bill.category %></td>
		      </tr>
		      <% end %>
		    </tbody>
		  </table>
    </div>
    <div class="col-sm-2" style="margin-top: 0px">
    	<h5>Search by Title, Bill Number, Category, and Primary Committee</h5>
      <%= form_tag admin_bills_path, :method => 'get'  do %>
		    <%= text_field_tag :search, params[:search]%>
		    <%= submit_tag "Search" %>
		  <% end %>
    </div>
    <%= will_paginate @bills %>
  </div>
</div>

app/views/admin/bills/show.erb
<div style="text-align:center">
	<h4><%=@bill.bill_num + ": " + @bill.title%></h4>
		<%if @xfile != nil%>
		<h4><%=link_to "This bill has a cross filed bill: " + @xfile.bill_num + ". Click here to view that bill", admin_bill_path(@xfile)%></h4>
	<%end%>
	<h4>Primary Hearing Date - House of Origin: <%=@bill.primary_hearing_date_origin%></h4>
	<h4>Primary Hearing Date - Opposite House: <%=@bill.primary_hearing_date_opposite%></h4>
	<h4>Official Description:</h4><%=@bill.synopsis%>
	<br>
	<h4>Simplified Description:</h4><%=@bill.description%>
</div>
<%=link_to "Back to edit page", edit_admin_bill_path(@bill)%>
<br>
<%=link_to "Back to Index", admin_bills_path%>

app/views/bills/index.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-10">
    	<table class="table table-striped">
		    <thead>
		      <tr>
		        <th style="width:10%">Bill Number</th>
		        <th style="width:40%">Title</th>
		        <th style="width:30%">Primary Committee</th>
		        <th>Category</th>
		      </tr>
		    </thead>
		    <tbody>
		    	<% @bills.each do |bill| %>
		      <tr>
		        <td><%= link_to bill.bill_num, bill_path(bill) %></td>
		        <td><%= bill.title %></td>
		        <td><%= bill.committee_primary_origin %></td>
		        <td><%= bill.category %></td>
		      </tr>
		      <% end %>
		    </tbody>
		  </table>
    </div>
    <div class="col-sm-2" style="margin-top: 0px">
    	<h5>Search by Title, Bill Number, Category and Primary Committee</h5>
      <%= form_tag bills_path, :method => 'get'  do %>
		    <%= text_field_tag :search, params[:search]%>
		    <%= submit_tag "Search" %>
		  <% end %>
    </div>
    <%= will_paginate @bills %>
  </div>
</div>

app/views/bills/show.erb
<div style="text-align:center">
	<h4><%=@bill.bill_num + ": " + @bill.title%></h4>
	<%if @xfile != nil%>
		<h4><%=link_to "This bill has a cross filed bill: " + @xfile.bill_num + ". Click here to view that bill", bill_path(@xfile)%></h4>
	<%end%>
	<h4>Primary Hearing Date - House of Origin: <%=@bill.primary_hearing_date_origin%></h4>
	<h4>Primary Hearing Date - Opposite House: <%=@bill.primary_hearing_date_opposite%></h4>
	<h4>Official Description:</h4><%=@bill.synopsis%>
	<br>
	<h4>Simplified Description:</h4><%=@bill.description%>
</div>
<%=link_to "Back to Index", bills_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tutorial</title>
      <%= stylesheet_link_tag    "application" %>
      <%= javascript_include_tag "application" %>
      <%= csrf_meta_tags %>
  </head>
  <body>
  <div>
    <p id="notice"><%= flash[:notice] %></p>
    <p id="alert"><%= flash[:alert] %></p>
  </div>
  <%= yield %>

  </body>
</html>

app/views/static_pages/home.erb

<div class="jumbotron">
  <h1 class="display-3">Welcome to the Maryland Legislative Coalition!</h1>
  <p class="lead">Here you can find all of the proposed legislation in Maryland for the 2018 session!</p>
  <p>Below are high impact bills this session</p>
  <p class="lead">
    <a class="btn btn-primary btn-lg" href="/bills" role="button">Search Bills!</a>
  </p>
</div>


<div class="row" style="margin-left: 20px; margin-right: 20px">
  <div class="col-sm-6">
    <div class="card text-center" style="border: 1px solid">
      <div class="card-block">
        <h3 class="card-title"><%= @billOne.bill_num %></h3>
        <p class="card-text"><%= @billOne.description %></p>
        <%= link_to 'Learn More', bill_path(@billOne), :class => "btn btn-primary" %>
      </div>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="card text-center" style="border: 1px solid">
      <div class="card-block">
        <h3 class="card-title"><%= @billTwo.bill_num %></h3>
        <p class="card-text"><%= @billTwo.description %></p>
        <%= link_to 'Learn More', bill_path(@billTwo), :class => "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>